onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /axi_tb_top/m_inf/aclk
add wave -noupdate /axi_tb_top/m_inf/arstn
add wave -noupdate /axi_tb_top/m_inf/awid
add wave -noupdate /axi_tb_top/m_inf/awaddr
add wave -noupdate /axi_tb_top/m_inf/awlen
add wave -noupdate /axi_tb_top/m_inf/awsize
add wave -noupdate /axi_tb_top/m_inf/awbrust
add wave -noupdate /axi_tb_top/m_inf/awready
add wave -noupdate /axi_tb_top/m_inf/awvalid
add wave -noupdate /axi_tb_top/m_inf/wid
add wave -noupdate /axi_tb_top/m_inf/wdata
add wave -noupdate /axi_tb_top/m_inf/wstrob
add wave -noupdate /axi_tb_top/m_inf/wlast
add wave -noupdate /axi_tb_top/m_inf/wready
add wave -noupdate /axi_tb_top/m_inf/wvalid
add wave -noupdate /axi_tb_top/m_inf/bid
add wave -noupdate /axi_tb_top/m_inf/bresp
add wave -noupdate /axi_tb_top/m_inf/bready
add wave -noupdate /axi_tb_top/m_inf/bvalid
add wave -noupdate /axi_tb_top/m_inf/arid
add wave -noupdate /axi_tb_top/m_inf/araddr
add wave -noupdate /axi_tb_top/m_inf/arlen
add wave -noupdate /axi_tb_top/m_inf/arsize
add wave -noupdate /axi_tb_top/m_inf/arbrust
add wave -noupdate /axi_tb_top/m_inf/arready
add wave -noupdate /axi_tb_top/m_inf/arvalid
add wave -noupdate /axi_tb_top/m_inf/rid
add wave -noupdate /axi_tb_top/m_inf/rdata
add wave -noupdate /axi_tb_top/m_inf/rresp
add wave -noupdate /axi_tb_top/m_inf/rlast
add wave -noupdate /axi_tb_top/m_inf/rready
add wave -noupdate /axi_tb_top/m_inf/rvalid
add wave -noupdate /axi_tb_top/m_inf/mas_drv_cb/mas_drv_cb_event
add wave -noupdate /axi_tb_top/m_inf/mas_mon_cb/mas_mon_cb_event
add wave -noupdate /axi_tb_top/s_inf/clk
add wave -noupdate /axi_tb_top/s_inf/rst
add wave -noupdate /axi_tb_top/s_inf/AWID
add wave -noupdate /axi_tb_top/s_inf/AWADDR
add wave -noupdate /axi_tb_top/s_inf/AWLEN
add wave -noupdate /axi_tb_top/s_inf/AWSIZE
add wave -noupdate /axi_tb_top/s_inf/AWBURST
add wave -noupdate /axi_tb_top/s_inf/AWVALID
add wave -noupdate /axi_tb_top/s_inf/AWREADY
add wave -noupdate /axi_tb_top/s_inf/WID
add wave -noupdate /axi_tb_top/s_inf/WDATA
add wave -noupdate /axi_tb_top/s_inf/WSTRB
add wave -noupdate /axi_tb_top/s_inf/WLAST
add wave -noupdate /axi_tb_top/s_inf/WREADY
add wave -noupdate /axi_tb_top/s_inf/WVALID
add wave -noupdate /axi_tb_top/s_inf/BID
add wave -noupdate /axi_tb_top/s_inf/BREADY
add wave -noupdate /axi_tb_top/s_inf/BVALID
add wave -noupdate /axi_tb_top/s_inf/BRESP
add wave -noupdate /axi_tb_top/s_inf/ARID
add wave -noupdate /axi_tb_top/s_inf/ARADDR
add wave -noupdate /axi_tb_top/s_inf/ARLEN
add wave -noupdate /axi_tb_top/s_inf/ARSIZE
add wave -noupdate /axi_tb_top/s_inf/ARBURST
add wave -noupdate /axi_tb_top/s_inf/ARVALID
add wave -noupdate /axi_tb_top/s_inf/ARREADY
add wave -noupdate /axi_tb_top/s_inf/RID
add wave -noupdate /axi_tb_top/s_inf/RDATA
add wave -noupdate /axi_tb_top/s_inf/RRSEP
add wave -noupdate /axi_tb_top/s_inf/RLAST
add wave -noupdate /axi_tb_top/s_inf/RVALID
add wave -noupdate /axi_tb_top/s_inf/RREADY
add wave -noupdate /axi_tb_top/s_inf/RRESP
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {25 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 193
configure wave -valuecolwidth 76
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {111 ns}
